allowBuilds:
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - '@img/sharp-darwin-arm64@0.35.3'
  - '@img/sharp-darwin-x64@0.35.3'
  - '@img/sharp-freebsd-wasm32@0.35.3'
  - '@img/sharp-linux-arm64@0.35.3'
  - '@img/sharp-linux-arm@0.35.3'
  - '@img/sharp-linux-ppc64@0.35.3'
  - '@img/sharp-linux-riscv64@0.35.3'
  - '@img/sharp-linux-s390x@0.35.3'
  - '@img/sharp-linux-x64@0.35.3'
  - '@img/sharp-linuxmusl-arm64@0.35.3'
  - '@img/sharp-linuxmusl-x64@0.35.3'
  - '@img/sharp-wasm32@0.35.3'
  - '@img/sharp-webcontainers-wasm32@0.35.3'
  - '@img/sharp-win32-arm64@0.35.3'
  - '@img/sharp-win32-ia32@0.35.3'
  - '@img/sharp-win32-x64@0.35.3'
  - sharp@0.35.3
  - '@takumi-rs/core-darwin-arm64@2.4.0'
  - '@takumi-rs/core-darwin-x64@2.4.0'
  - '@takumi-rs/core-linux-arm64-gnu@2.4.0'
  - '@takumi-rs/core-linux-arm64-musl@2.4.0'
  - '@takumi-rs/core-linux-x64-gnu@2.4.0'
  - '@takumi-rs/core-linux-x64-musl@2.4.0'
  - '@takumi-rs/core-win32-arm64-msvc@2.4.0'
  - '@takumi-rs/core-win32-x64-msvc@2.4.0'
  - '@takumi-rs/core@2.4.0'
  - '@takumi-rs/helpers@2.4.0'
  - '@takumi-rs/wasm@2.4.0'
  - astro@7.1.3
  - takumi-js@2.4.0
