#:schema node_modules/wrangler/config-schema.json
name = "portfolio"
compatibility_date = "2025-03-8"
compatibility_flags = [ "nodejs_compat_v2" ]
pages_build_output_dir = "./dist"

[vars]
NODE_VERSION = 22